"""empty message

Revision ID: 5c1c8a4735ec
Revises: a6bbcc05dac0
Create Date: 2022-10-15 15:00:30.160214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c1c8a4735ec"
down_revision = "a6bbcc05dac0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todolists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("todos", sa.Column("list_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "todos", "todolists", ["list_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.drop_column("todos", "list_id")
    op.drop_table("todolists")
    # ### end Alembic commands ###
