"""empty message

Revision ID: a6a747619653
Revises: a6fed6f4708a
Create Date: 2022-10-15 15:25:41.564654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a747619653'
down_revision = 'a6fed6f4708a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=False))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
